<a href="https://colab.research.google.com/github/SaidFlores22/Valores-Nulos/blob/main/Actividad_2_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Actividad 2.2 : Valores Nulos**
## Said Arturo Flores Nieto
## A01703477
## **EQUIPO 6**

In [54]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [55]:
from google.colab import files
files.upload()

{}

In [56]:
fact = pd.read_excel("Datos de Facturación.xlsx")
det = pd.read_csv("Detalle precios y productos fabricados 2022.csv")
gyc20 = pd.read_excel("Gastos y costos 20-23.xlsx", sheet_name = '2020', header = 5)
gyc21 = pd.read_excel("Gastos y costos 20-23.xlsx", sheet_name = '2021', header = 3)
gyc22 = pd.read_excel("Gastos y costos 20-23.xlsx", sheet_name = '2022', header = 3)
gyc23 = pd.read_excel("Gastos y costos 20-23.xlsx", sheet_name = '2023', header = 3)

In [57]:
fact.head()

,CVE_DOC,CVE_CLPV,STATUS,CVE_VEND,FECHAELAB,FECHA_DOC,FECHA_ENT,FECHA_VEN,FECHA_CANCELA,CAN_TOT,DES_TOT,DES_FIN
0,F29414,2465,C,1.0,2019-09-03 08:58:42,2019-09-03,2019-09-03 00:00:00,2019-09-18,2019-09-04,3980.00,0.0,0
1,F29415,3926,C,1.0,2019-09-03 09:55:14,2019-09-03,2019-09-03 00:00:00,2019-10-03,2019-09-03,1550.00,0.0,0
2,F29416,3926,C,1.0,2019-09-03 13:25:33,2019-09-03,2019-09-03 00:00:00,2019-10-03,2019-09-03,1550.00,0.0,0
3,F29417,3926,C,1.0,2019-09-03 13:33:23,2019-09-03,2019-09-03 00:00:00,2019-10-03,2019-09-17,1550.00,0.0,0
4,F29418,6813,C,2.0,2019-09-03 14:23:45,2019-09-03,2019-09-03 00:00:00,2019-09-03,2019-09-10,2435.44,0.0,0

In [58]:
det.head()

,CVE_DOC,FECHA_DOC,NOMBRE,NOMBRE.1,CANT,CVE_ART,DESCR,PRECIO_UNITARIO,COSTO_UNITARIO,COSTO_UNITARIO_CALCULADO,SUBTOTAL_PARTIDA,COSTO_TOTAL_CALCULADO,MARGEN_UNITARIO_CALCULADO,MARGEN_TOTAL_CALCULADO
0,F37034,05/01/2022 00:00,LETICIA RAMIREZ HERNANDEZ,PÚBLICO EN GENERAL,1,TUE00244,"TUB COBRE 5/16""ØX165MM CIRCULA1.5KW127V",$434.48,$52.80,$52.80,$434.48,$52.80,$381.68,$381.68
1,F37036,05/01/2022 00:00,LETICIA RAMIREZ HERNANDEZ,JUAN ANTONIO RESENDIZ UGALDE,1,TUA00028,"TUA U"" 5/16 ØX250MM 1200W 120V TAP1""NPT","$1,264.05",$327.18,$327.18,"$1,264.05",$327.18,$936.87,$936.87
2,F37041,05/01/2022 00:00,DIEGO ARMANDO LEON DURAN,ANA BARBARA CRUZ PALACIOS,7,TP0007,TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 7 MT,$551.61,$177.68,$177.68,"$3,861.29","$1,243.73",$373.94,"$2,617.56"
3,F37042,05/01/2022 00:00,DIEGO ARMANDO LEON DURAN,OMAR RODRIGUEZ GOMEZ,1,TP0001,TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 1 MT,$140,$38.96,$38.96,$140,$38.96,$101.04,$101.04
4,F37043,05/01/2022 00:00,LETICIA RAMIREZ HERNANDEZ,PÚBLICO EN GENERAL,2,BP00242,BAN P INOX 115MMX235MM 1000W 127V T/TOR,$172.41,$101.71,$101.71,$344.83,$203.42,$70.71,$141.41

In [59]:
gyc20.head()

,FECHA,FOLIO,UUID,RFC,PROVEEDOR,TIPO GASTO,GASTO,DESCRIPCION,TC,IMPORTE,IVA,RET ISR,RET IVA,TOTAL MX,TOTAL SAT,TIPO,STATUS,POLIZA,Columna1
0,2020-01-01,39408,BD20F436-72CC-4BE2-AD37-5999D71AA391,ARE080115PBA,ARSI RENTA SA DE CV,MAQUINARIA,NaN,"Descripción: REVOLVEDORA, Modelo: ULTRAMP9A, M...",1.0,0.00,2248.28,0.0,0.0,2248.28,16300.00,I,Vigente,NaN,14051.72
1,2020-01-01,0001010100750847116902,85AEAC2E-6395-44A0-9CB9-754D06893375,BNM840515VB1,"BANCO NACIONAL DE MEXICO, S.A.",COMISION BANCARIA,NaN,COMISION COBRADA,1.0,490.00,78.40,0.0,0.0,568.40,568.40,I,Vigente,NaN,0.00
2,2020-01-01,0001010100752163714102,BD0DFE85-D776-41CB-9C5C-4FA7923E687A,BNM840515VB1,"BANCO NACIONAL DE MEXICO, S.A.",COMISION BANCARIA,NaN,COMISION COBRADA,1.0,195.00,31.20,0.0,0.0,226.20,226.20,I,Vigente,NaN,0.00
3,2020-01-01,3663,EF4504D6-830D-415C-AF03-80CF54C5E28E,PSS120625C86,PROMOTORA DE SERVICIOS Y SOLUCIONES EMPRESARIA...,HONORARIOS CONTABLES,NaN,HONORARIOS CONTABLES\nDEL MES DE ENERO DEL 2020.,1.0,10694.25,1711.08,0.0,0.0,12405.33,12405.33,I,Vigente,NaN,0.00
4,2020-01-01,2849,EC2F4AA4-BA64-4E2E-A5B7-4EBBE042D6D3,ENA7006081P0,ELECTROTERMICA NACIONAL SA DE CV,COMPRAS,NaN,Pago,1.0,0.00,NaN,0.0,0.0,0.00,0.00,P,Vigente,NaN,0.00

In [60]:
gyc21.head()

,FECHA,FOLIO,UUID,RFC,PROVEEDOR,TIPO GASTO,DESCRIPCION,MP,TC,IMPORTE,IVA,RET ISR,RET IVA,TOTAL MX,TOTAL SAT,TIPO,STATUS,POLIZA
0,2021-01-01,0001010100750847116902,71B4C8B9-8DAA-47CC-AD47-9DD90AA5AF6B,BNM840515VB1,"BANCO NACIONAL DE MEXICO, S.A.",COMISION BANCARIA,COMISION COBRADA,PUE,1.0,490.00,78.40,0.0,0.0,568.4,568.4,I,Vigente,0
1,2021-01-01,0001010100752163714102,B8AEDE83-CC76-404C-A611-6B5A87BA561F,BNM840515VB1,"BANCO NACIONAL DE MEXICO, S.A.",COMISION BANCARIA,COMISION COBRADA,PUE,1.0,345.00,55.20,0.0,0.0,400.2,400.2,I,Vigente,0
2,2021-01-01,19788,19B9B2C2-DF58-E24D-B43A-3FC4D5A929E7,ESI9612311E7,"ELECTRONICOS Y SIMILARES, S.A. DE C.V.",COMPRAS,MOTO E7 PLUS AZUL 64GB 4RAM,PUE,1.0,3447.41,551.59,0.0,0.0,3999.0,3999.0,I,Vigente,0
3,2021-01-01,211781,EAB26414-DD9A-4E8F-9F5C-05FE24D98E48,BLE1512082R9,BEPENSA LEASING S.A. DE C.V.,ARRENDAMIENTO FINANCIERO,AA RENTA EXIGIBLE CL0000006876 6/36 de 03/12/2...,PPD,1.0,5551.38,888.22,0.0,0.0,6439.6,6439.6,I,Vigente,0
4,2021-01-01,211782,C16F79B5-FB35-4BFC-AF84-708B24F500BB,BLE1512082R9,BEPENSA LEASING S.A. DE C.V.,ARRENDAMIENTO FINANCIERO,AA RENTA EXIGIBLE CL0000006877 6/36 de 03/12/2...,PPD,1.0,5551.98,888.32,0.0,0.0,6440.3,6440.3,I,Vigente,0

In [61]:
gyc22.head()

,Fecha,Folio,UUID,RFC,Proveedor,TIPO GASTO,Descripción,MP,TC,Importe,IVA,RET ISR,RET IVA,Otros,TOTAL MX,TOTAL SAT,Tipo,Status,Poliza
0,2022-01-01,280108,9DA0E63F-1D47-441F-93D7-C2E05AE4D35E,BLE1512082R9,BEPENSA LEASING S.A. DE C.V.,ARRENDAMIENTO FINANCIERO,AA RENTA EXIGIBLE CL0000006876 18/36 de 03/12/...,PPD,1.0,5551.38,888.22,0.0,0.0,NaN,6439.6,6439.6,I,Vigente,PE02-ENE22
1,2022-01-01,280109,7E00E776-A839-4D57-B291-411109164B2F,BLE1512082R9,BEPENSA LEASING S.A. DE C.V.,ARRENDAMIENTO FINANCIERO,AA RENTA EXIGIBLE CL0000006877 18/36 de 03/12/...,PPD,1.0,5551.98,888.32,0.0,0.0,NaN,6440.3,6440.3,I,Vigente,PE03-ENE22
2,2022-01-01,007817297284,BB6585C1-3B54-4130-AFD0-1867C3764821,BNM840515VB1,"BANCO NACIONAL DE MEXICO, S.A.",COMISION BANCARIA,Servicios de Facturación,PUE,1.0,0.00,0.00,0.0,0.0,NaN,0.0,0.0,I,Vigente,NaN
3,2022-01-01,5595,B5E4B4EB-6C2F-11EC-BB9D-00155D014009,ZEGC530520V4A,CARLOS ENRIQUE ZERMEÑO GUTIERREZ,COMPRAS,Pago,NaN,1.0,0.00,0.00,0.0,0.0,NaN,0.0,0.0,P,Vigente,NaN
4,2022-01-01,5614,BB6756D1-6CCD-11EC-947D-00155D014407,ZEGC530520V4A,CARLOS ENRIQUE ZERMEÑO GUTIERREZ,COMPRAS,Pago,NaN,1.0,0.00,0.00,0.0,0.0,NaN,0.0,0.0,P,Vigente,NaN

In [62]:
gyc23.head()

,Fecha,Folio,UUID,RFC,Proveedor,TIPO GASTO,Descripción,MP,FP,TC,Importe,IVA,RET ISR,RET IVA,Otros,TOTAL MX,TOTAL SAT,Tipo,Status,Poliza
0,2023-01-01,31,49536321-60A4-523E-A32F-E8BDF5C2276E,AAE6411055P8,AESA ARTICULOS ELECTRICOS,COMPRAS,Pago,NaN,NaN,1.0,0.00,0.00,0.0,0.0,NaN,0.00,0.00,P,Vigente,NaN
1,2023-01-01,38,20FBB63B-D550-512F-9668-EEC6F983CEB7,AAE6411055P8,AESA ARTICULOS ELECTRICOS,COMPRAS,Pago,NaN,NaN,1.0,0.00,0.00,0.0,0.0,NaN,0.00,0.00,P,Vigente,NaN
2,2023-01-01,341932,DB8C4388-D4E0-4F0C-A09C-77C773257F44,BLE1512082R9,BEPENSA LEASING S.A. DE C.V.,ARRENDAMIENTO FINANCIERO,AA RENTA EXIGIBLE CL0000006876 30/36 de 03/12/...,PPD,99.0,1.0,5551.38,888.22,0.0,0.0,NaN,6439.60,6439.60,I,Vigente,PE01-ENE23
3,2023-01-01,341933,A81A63F5-D5EC-4601-803E-375AF9CC5021,BLE1512082R9,BEPENSA LEASING S.A. DE C.V.,ARRENDAMIENTO FINANCIERO,AA RENTA EXIGIBLE CL0000006877 30/36 de 03/12/...,PPD,99.0,1.0,5551.98,888.32,0.0,0.0,NaN,6440.30,6440.30,I,Vigente,PE02-ENE23
4,2023-01-01,342205,DCC10492-DE51-4C87-8430-5676FBF81931,BLE1512082R9,BEPENSA LEASING S.A. DE C.V.,ARRENDAMIENTO FINANCIERO,AA RENTA EXIGIBLE CL0000009486 5/48 de 03/12/2...,PPD,99.0,1.0,8454.37,1352.70,0.0,0.0,NaN,9807.07,9807.07,I,Vigente,PE03-ENE23

In [63]:
from numpy import integer

print("\033[1m" + "\n DATOS NULOS DE FACTURACIÓN: " + str(len(fact)) + "\033[0m" )
print(fact.isnull().sum())
print("\033[1m" + "\n DATOS NULOS DE DETALLES DE PRECIOS 2022: " + str(len(det)) + "\033[0m")
print(det.isnull().sum())
print("\033[1m" + "\n DATOS NULOS DE GASTOS Y COSTOS 2020: " + str(len(gyc20)) + "\033[0m")
print(gyc20.isnull().sum())
print("\033[1m" + "\n DATOS NULOS DE GASTOS Y COSTOS 2021: " + str(len(gyc21)) + "\033[0m")
print(gyc21.isnull().sum())
print("\033[1m" + "\n DATOS NULOS DE GASTOS Y COSTOS 2022: " + str(len(gyc22)) + "\033[0m")
print(gyc22.isnull().sum())
print("\033[1m" + "\n DATOS NULOS DE GASTOS Y COSTOS 2023: " + str(len(gyc23)) + "\033[0m")
print(gyc23.isnull().sum())

 DATOS NULOS DE FACTURACIÓN: 10895
CVE_DOC              0
CVE_CLPV             0
STATUS               0
CVE_VEND            48
FECHAELAB            0
FECHA_DOC            0
FECHA_ENT            2
FECHA_VEN            0
FECHA_CANCELA    10537
CAN_TOT              0
DES_TOT              0
DES_FIN              0
dtype: int64

 DATOS NULOS DE DETALLES DE PRECIOS 2022: 1426
CVE_DOC                      0
FECHA_DOC                    0
NOMBRE                       2
NOMBRE.1                     0
CANT                         0
CVE_ART                      0
DESCR                        0
PRECIO_UNITARIO              0
COSTO_UNITARIO               0
COSTO_UNITARIO_CALCULADO     0
SUBTOTAL_PARTIDA             0
COSTO_TOTAL_CALCULADO        0
MARGEN_UNITARIO_CALCULADO    0
MARGEN_TOTAL_CALCULADO       0
dtype: int64

 DATOS NULOS DE GASTOS Y COSTOS 2020: 3342
FECHA             0
FOLIO           189
UUID              0
RFC               0
PROVEEDOR         0
TIPO GASTO        0
GASTO          2502
DESCRIPCION       0
TC              391
IMPORTE          34
IVA             268
RET ISR           0
RET IVA           0
TOTAL MX          0
TOTAL SAT         0
TIPO              1
STATUS            0
POLIZA         3321
Columna1          0
dtype: int64

 DATOS NULOS DE GASTOS Y COSTOS 2021: 3035
FECHA             0
FOLIO           147
UUID              0
RFC               0
PROVEEDOR         0
TIPO GASTO        0
DESCRIPCION       0
MP              654
TC                0
IMPORTE           0
IVA               0
RET ISR           0
RET IVA           0
TOTAL MX          0
TOTAL SAT         0
TIPO              0
STATUS            0
POLIZA         2372
dtype: int64

 DATOS NULOS DE GASTOS Y COSTOS 2022: 2577
Fecha             0
Folio           102
UUID              0
RFC               0
Proveedor         0
TIPO GASTO        0
Descripción       0
MP              553
TC              636
Importe           0
IVA               0
RET ISR           0
RET IVA           0
Otros          2577
TOTAL MX          0
TOTAL SAT         0
Tipo              0
Status            0
Poliza          801
dtype: int64

 DATOS NULOS DE GASTOS Y COSTOS 2023: 397
Fecha            0
Folio           13
UUID             0
RFC              0
Proveedor        0
TIPO GASTO       8
Descripción      0
MP              71
FP              71
TC               0
Importe          0
IVA              0
RET ISR          0
RET IVA          0
Otros          397
TOTAL MX         0
TOTAL SAT        0
Tipo             0
Status           0
Poliza         115
dtype: int64

### **FACTURACIÓN**

En este caso uitilizamos sustituimos los valores nulos por un string ya establecido "--", con el fin de identificar cuando no contamos con dicho valor, a pesar de que la clave del vendedor es del tipo string, no consideramos relevante que se mantenga así, ya que no se utilizara para realizar operaciones, sino solo para conocer que vendedor realizo la operación y en la fecha de cancelación al ser tantos datos nulos y al observar que la fecha de entrega no es del tipo datetime, no consideramos que relevante mantener el tipo datetime, por lo cual decidimos usar ese string, ya que el poner otra fecha nos diría que si se cancelo la factura, lo cual no sucedio.

In [64]:
fact.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10895 entries, 0 to 10894
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   CVE_DOC        10895 non-null  object
 1   CVE_CLPV       10895 non-null  object
 2   STATUS         10895 non-null  object
 3   CVE_VEND       10847 non-null  float64
 4   FECHAELAB      10895 non-null  datetime64[ns]
 5   FECHA_DOC      10895 non-null  datetime64[ns]
 6   FECHA_ENT      10893 non-null  object
 7   FECHA_VEN      10895 non-null  datetime64[ns]
 8   FECHA_CANCELA  358 non-null    datetime64[ns]
 9   CAN_TOT        10895 non-null  float64
 10  DES_TOT        10895 non-null  float64
 11  DES_FIN        10895 non-null  int64
dtypes: datetime64[ns](4), float64(3), int64(1), object(4)
memory usage: 1021.5+ KB

In [65]:
fact['CVE_VEND'] = fact['CVE_VEND'].fillna('--')
fact['FECHA_CANCELA'] = fact['FECHA_CANCELA'].fillna('--')
fact['FECHA_ENT'] = fact['FECHA_ENT'].fillna('--')

In [66]:
fact.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10895 entries, 0 to 10894
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   CVE_DOC        10895 non-null  object
 1   CVE_CLPV       10895 non-null  object
 2   STATUS         10895 non-null  object
 3   CVE_VEND       10895 non-null  object
 4   FECHAELAB      10895 non-null  datetime64[ns]
 5   FECHA_DOC      10895 non-null  datetime64[ns]
 6   FECHA_ENT      10895 non-null  object
 7   FECHA_VEN      10895 non-null  datetime64[ns]
 8   FECHA_CANCELA  10895 non-null  object
 9   CAN_TOT        10895 non-null  float64
 10  DES_TOT        10895 non-null  float64
 11  DES_FIN        10895 non-null  int64
dtypes: datetime64[ns](3), float64(2), int64(1), object(6)
memory usage: 1021.5+ KB

### **Detalles de precios 2022**

En este caso de igual manera utilice el string "--" el cual solo servira para que los datos nulos no afecten el analisis, ya que este string nos dará a conocer si el nombre del vendedor falta.

In [67]:
det.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1426 entries, 0 to 1425
Data columns (total 14 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   CVE_DOC                    1426 non-null   object
 1   FECHA_DOC                  1426 non-null   object
 2   NOMBRE                     1424 non-null   object
 3   NOMBRE.1                   1426 non-null   object
 4   CANT                       1426 non-null   int64
 5   CVE_ART                    1426 non-null   object
 6   DESCR                      1426 non-null   object
 7   PRECIO_UNITARIO            1426 non-null   object
 8   COSTO_UNITARIO             1426 non-null   object
 9   COSTO_UNITARIO_CALCULADO   1426 non-null   object
 10  SUBTOTAL_PARTIDA           1426 non-null   object
 11  COSTO_TOTAL_CALCULADO      1426 non-null   object
 12  MARGEN_UNITARIO_CALCULADO  1426 non-null   object
 13  MARGEN_TOTAL_CALCULADO     1426 non-null   object
dtypes: int64(1), object(13)
memory usage: 156.1+ KB

In [68]:
det['NOMBRE'] = det['NOMBRE'].fillna('--')

In [69]:
det.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1426 entries, 0 to 1425
Data columns (total 14 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   CVE_DOC                    1426 non-null   object
 1   FECHA_DOC                  1426 non-null   object
 2   NOMBRE                     1426 non-null   object
 3   NOMBRE.1                   1426 non-null   object
 4   CANT                       1426 non-null   int64
 5   CVE_ART                    1426 non-null   object
 6   DESCR                      1426 non-null   object
 7   PRECIO_UNITARIO            1426 non-null   object
 8   COSTO_UNITARIO             1426 non-null   object
 9   COSTO_UNITARIO_CALCULADO   1426 non-null   object
 10  SUBTOTAL_PARTIDA           1426 non-null   object
 11  COSTO_TOTAL_CALCULADO      1426 non-null   object
 12  MARGEN_UNITARIO_CALCULADO  1426 non-null   object
 13  MARGEN_TOTAL_CALCULADO     1426 non-null   object
dtypes: int64(1), object(13)
memory usage: 156.1+ KB

### **Gastos y costos 2020**

En este caso todas las columnas con datos faltantes que tuvieran tipos de datos object, sus datos nulos fueron sustituídos por el string "--", de igual manera solo para poder identificar que es un dato faltante y que no afecte el análisis.
Por otra parte, en el tipo de cambio, se sustituyeron los datos nulos por el valor 1, ya que esto significa que se maneja la misma moneda, es decir en pesos.
Finalmente, para el importe y el iva se utilizó la mediana, con el fin de no perder información relevante y que los valores atipicos no afectaran el analisis como en el caso del promedio.

In [70]:
gyc20.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3342 entries, 0 to 3341
Data columns (total 19 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   FECHA        3342 non-null   datetime64[ns]
 1   FOLIO        3153 non-null   object
 2   UUID         3342 non-null   object
 3   RFC          3342 non-null   object
 4   PROVEEDOR    3342 non-null   object
 5   TIPO GASTO   3342 non-null   object
 6   GASTO        840 non-null    object
 7   DESCRIPCION  3342 non-null   object
 8   TC           2951 non-null   float64
 9   IMPORTE      3308 non-null   float64
 10  IVA          3074 non-null   float64
 11  RET ISR      3342 non-null   float64
 12  RET IVA      3342 non-null   float64
 13  TOTAL MX     3342 non-null   float64
 14  TOTAL SAT    3342 non-null   float64
 15  TIPO         3341 non-null   object
 16  STATUS       3342 non-null   object
 17  POLIZA       21 non-null     object
 18  Columna1     3342 non-null   float64
dtypes: datetime64[ns](1), float64(8), object(10)
memory usage: 496.2+ KB

In [71]:
gyc20['FOLIO'] = gyc20['FOLIO'].fillna('--')
gyc20['GASTO'] = gyc20['GASTO'].fillna('--')
gyc20['TC'] = gyc20['TC'].fillna(1)
gyc20['IMPORTE'] = gyc20['IMPORTE'].fillna(round(gyc20["IMPORTE"].median(),1))
gyc20['IVA'] = gyc20['IVA'].fillna(round(gyc20["IVA"].median(),1))
gyc20['TIPO'] = gyc20['TIPO'].fillna('--')
gyc20['POLIZA'] = gyc20['POLIZA'].fillna('--')

In [72]:
gyc20.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3342 entries, 0 to 3341
Data columns (total 19 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   FECHA        3342 non-null   datetime64[ns]
 1   FOLIO        3342 non-null   object
 2   UUID         3342 non-null   object
 3   RFC          3342 non-null   object
 4   PROVEEDOR    3342 non-null   object
 5   TIPO GASTO   3342 non-null   object
 6   GASTO        3342 non-null   object
 7   DESCRIPCION  3342 non-null   object
 8   TC           3342 non-null   float64
 9   IMPORTE      3342 non-null   float64
 10  IVA          3342 non-null   float64
 11  RET ISR      3342 non-null   float64
 12  RET IVA      3342 non-null   float64
 13  TOTAL MX     3342 non-null   float64
 14  TOTAL SAT    3342 non-null   float64
 15  TIPO         3342 non-null   object
 16  STATUS       3342 non-null   object
 17  POLIZA       3342 non-null   object
 18  Columna1     3342 non-null   float64
dtypes: datetime64[ns](1), float64(8), object(10)
memory usage: 496.2+ KB

### **Gastos y costos 2021**

En este caso las tres columnas en las que tenemos valores faltantes son del tipo de dato objecto, por lo que solo queremos identificarlos y que no nos afecten el análisis, por lo que se sustituyen con el string "--"

In [73]:
gyc21.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3035 entries, 0 to 3034
Data columns (total 18 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   FECHA        3035 non-null   datetime64[ns]
 1   FOLIO        2888 non-null   object
 2   UUID         3035 non-null   object
 3   RFC          3035 non-null   object
 4   PROVEEDOR    3035 non-null   object
 5   TIPO GASTO   3035 non-null   object
 6   DESCRIPCION  3035 non-null   object
 7   MP           2381 non-null   object
 8   TC           3035 non-null   float64
 9   IMPORTE      3035 non-null   float64
 10  IVA          3035 non-null   float64
 11  RET ISR      3035 non-null   float64
 12  RET IVA      3035 non-null   float64
 13  TOTAL MX     3035 non-null   float64
 14  TOTAL SAT    3035 non-null   float64
 15  TIPO         3035 non-null   object
 16  STATUS       3035 non-null   object
 17  POLIZA       663 non-null    object
dtypes: datetime64[ns](1), float64(7), object(10)
memory usage: 426.9+ KB

In [74]:
gyc21['FOLIO'] = gyc21['FOLIO'].fillna('--')
gyc21['MP'] = gyc21['MP'].fillna('--')
gyc21['POLIZA'] = gyc21['POLIZA'].fillna('--')

In [75]:
gyc21.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3035 entries, 0 to 3034
Data columns (total 18 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   FECHA        3035 non-null   datetime64[ns]
 1   FOLIO        3035 non-null   object
 2   UUID         3035 non-null   object
 3   RFC          3035 non-null   object
 4   PROVEEDOR    3035 non-null   object
 5   TIPO GASTO   3035 non-null   object
 6   DESCRIPCION  3035 non-null   object
 7   MP           3035 non-null   object
 8   TC           3035 non-null   float64
 9   IMPORTE      3035 non-null   float64
 10  IVA          3035 non-null   float64
 11  RET ISR      3035 non-null   float64
 12  RET IVA      3035 non-null   float64
 13  TOTAL MX     3035 non-null   float64
 14  TOTAL SAT    3035 non-null   float64
 15  TIPO         3035 non-null   object
 16  STATUS       3035 non-null   object
 17  POLIZA       3035 non-null   object
dtypes: datetime64[ns](1), float64(7), object(10)
memory usage: 426.9+ KB

### **Gastos y costos 2022**

Para este dataset tenemos 3 columnas con tipo de dato object, las cuales son Folio, MP y Poliza, de modo que como en los casos anteriores se les sustituye con "--", mientras que el tipo de cambio se sustituye a los valores nulos con 1 y el el caso de la columna otros al no tener un solo dato no nulo, se borra.

In [76]:
gyc22.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2577 entries, 0 to 2576
Data columns (total 19 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Fecha        2577 non-null   datetime64[ns]
 1   Folio        2475 non-null   object
 2   UUID         2577 non-null   object
 3   RFC          2577 non-null   object
 4   Proveedor    2577 non-null   object
 5   TIPO GASTO   2577 non-null   object
 6   Descripción  2577 non-null   object
 7   MP           2024 non-null   object
 8   TC           1941 non-null   float64
 9   Importe      2577 non-null   float64
 10  IVA          2577 non-null   float64
 11  RET ISR      2577 non-null   float64
 12  RET IVA      2577 non-null   float64
 13  Otros        0 non-null      float64
 14  TOTAL MX     2577 non-null   float64
 15  TOTAL SAT    2577 non-null   float64
 16  Tipo         2577 non-null   object
 17  Status       2577 non-null   object
 18  Poliza       1776 non-null   object
dtypes: datetime64[ns](1), float64(8), object(10)
memory usage: 382.6+ KB

In [77]:
gyc22['Folio'] = gyc22['Folio'].fillna('--')
gyc22['MP'] = gyc22['MP'].fillna('--')
gyc22['TC'] = gyc22['TC'].fillna(1)
gyc22['Poliza'] = gyc22['Poliza'].fillna('--')
gyc22 = gyc22.dropna(axis = 1)

In [78]:
gyc22.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2577 entries, 0 to 2576
Data columns (total 18 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Fecha        2577 non-null   datetime64[ns]
 1   Folio        2577 non-null   object
 2   UUID         2577 non-null   object
 3   RFC          2577 non-null   object
 4   Proveedor    2577 non-null   object
 5   TIPO GASTO   2577 non-null   object
 6   Descripción  2577 non-null   object
 7   MP           2577 non-null   object
 8   TC           2577 non-null   float64
 9   Importe      2577 non-null   float64
 10  IVA          2577 non-null   float64
 11  RET ISR      2577 non-null   float64
 12  RET IVA      2577 non-null   float64
 13  TOTAL MX     2577 non-null   float64
 14  TOTAL SAT    2577 non-null   float64
 15  Tipo         2577 non-null   object
 16  Status       2577 non-null   object
 17  Poliza       2577 non-null   object
dtypes: datetime64[ns](1), float64(7), object(10)
memory usage: 362.5+ KB

### **Gastos y costos 2023**

De igual manera que en el dataset anterior las columnas con tipo de dato object fueron sustituidas con "--", a excepción de la columna FP que tenía objeto flotante, la cual recibió la misma forma de sustitución de datos nulos, esto ya que, FP es un codigo que recibe cada municipio que es MP, por lo que no tiene gran relevancia para realizar operaciones o un análisis cuantitativo, por lo que no es relevante mantener el tipo de dato, así mismo, la columna otros se elimino.

In [79]:
gyc23.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 397 entries, 0 to 396
Data columns (total 20 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Fecha        397 non-null    datetime64[ns]
 1   Folio        384 non-null    object
 2   UUID         397 non-null    object
 3   RFC          397 non-null    object
 4   Proveedor    397 non-null    object
 5   TIPO GASTO   389 non-null    object
 6   Descripción  397 non-null    object
 7   MP           326 non-null    object
 8   FP           326 non-null    float64
 9   TC           397 non-null    float64
 10  Importe      397 non-null    float64
 11  IVA          397 non-null    float64
 12  RET ISR      397 non-null    float64
 13  RET IVA      397 non-null    float64
 14  Otros        0 non-null      float64
 15  TOTAL MX     397 non-null    float64
 16  TOTAL SAT    397 non-null    float64
 17  Tipo         397 non-null    object
 18  Status       397 non-null    object
 19  Poliza       282 non-null    object
dtypes: datetime64[ns](1), float64(9), object(10)
memory usage: 62.2+ KB

In [80]:
gyc23['Folio'] = gyc23['Folio'].fillna('--')
gyc23['TIPO GASTO'] = gyc23['TIPO GASTO'].fillna('--')
gyc23['MP'] = gyc23['MP'].fillna('--')
gyc23['FP'] = gyc23['FP'].fillna('--')
gyc23['Poliza'] = gyc23['Poliza'].fillna('--')
gyc23 = gyc23.dropna(axis = 1)

In [81]:
gyc23.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 397 entries, 0 to 396
Data columns (total 19 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Fecha        397 non-null    datetime64[ns]
 1   Folio        397 non-null    object
 2   UUID         397 non-null    object
 3   RFC          397 non-null    object
 4   Proveedor    397 non-null    object
 5   TIPO GASTO   397 non-null    object
 6   Descripción  397 non-null    object
 7   MP           397 non-null    object
 8   FP           397 non-null    object
 9   TC           397 non-null    float64
 10  Importe      397 non-null    float64
 11  IVA          397 non-null    float64
 12  RET ISR      397 non-null    float64
 13  RET IVA      397 non-null    float64
 14  TOTAL MX     397 non-null    float64
 15  TOTAL SAT    397 non-null    float64
 16  Tipo         397 non-null    object
 17  Status       397 non-null    object
 18  Poliza       397 non-null    object
dtypes: datetime64[ns](1), float64(7), object(11)
memory usage: 59.1+ KB

In [82]:
print("\033[1m" + "\n DATOS NULOS DE FACTURACIÓN: " + str(len(fact)) + "\033[0m" )
print(fact.isnull().sum())
print("\033[1m" + "\n DATOS NULOS DE DETALLES DE PRECIOS 2022: " + str(len(det)) + "\033[0m")
print(det.isnull().sum())
print("\033[1m" + "\n DATOS NULOS DE GASTOS Y COSTOS 2020: " + str(len(gyc20)) + "\033[0m")
print(gyc20.isnull().sum())
print("\033[1m" + "\n DATOS NULOS DE GASTOS Y COSTOS 2021: " + str(len(gyc21)) + "\033[0m")
print(gyc21.isnull().sum())
print("\033[1m" + "\n DATOS NULOS DE GASTOS Y COSTOS 2022: " + str(len(gyc22)) + "\033[0m")
print(gyc22.isnull().sum())
print("\033[1m" + "\n DATOS NULOS DE GASTOS Y COSTOS 2023: " + str(len(gyc23)) + "\033[0m")
print(gyc23.isnull().sum())

 DATOS NULOS DE FACTURACIÓN: 10895
CVE_DOC          0
CVE_CLPV         0
STATUS           0
CVE_VEND         0
FECHAELAB        0
FECHA_DOC        0
FECHA_ENT        0
FECHA_VEN        0
FECHA_CANCELA    0
CAN_TOT          0
DES_TOT          0
DES_FIN          0
dtype: int64

 DATOS NULOS DE DETALLES DE PRECIOS 2022: 1426
CVE_DOC                      0
FECHA_DOC                    0
NOMBRE                       0
NOMBRE.1                     0
CANT                         0
CVE_ART                      0
DESCR                        0
PRECIO_UNITARIO              0
COSTO_UNITARIO               0
COSTO_UNITARIO_CALCULADO     0
SUBTOTAL_PARTIDA             0
COSTO_TOTAL_CALCULADO        0
MARGEN_UNITARIO_CALCULADO    0
MARGEN_TOTAL_CALCULADO       0
dtype: int64

 DATOS NULOS DE GASTOS Y COSTOS 2020: 3342
FECHA          0
FOLIO          0
UUID           0
RFC            0
PROVEEDOR      0
TIPO GASTO     0
GASTO          0
DESCRIPCION    0
TC             0
IMPORTE        0
IVA            0
RET ISR        0
RET IVA        0
TOTAL MX       0
TOTAL SAT      0
TIPO           0
STATUS         0
POLIZA         0
Columna1       0
dtype: int64

 DATOS NULOS DE GASTOS Y COSTOS 2021: 3035
FECHA          0
FOLIO          0
UUID           0
RFC            0
PROVEEDOR      0
TIPO GASTO     0
DESCRIPCION    0
MP             0
TC             0
IMPORTE        0
IVA            0
RET ISR        0
RET IVA        0
TOTAL MX       0
TOTAL SAT      0
TIPO           0
STATUS         0
POLIZA         0
dtype: int64

 DATOS NULOS DE GASTOS Y COSTOS 2022: 2577
Fecha          0
Folio          0
UUID           0
RFC            0
Proveedor      0
TIPO GASTO     0
Descripción    0
MP             0
TC             0
Importe        0
IVA            0
RET ISR        0
RET IVA        0
TOTAL MX       0
TOTAL SAT      0
Tipo           0
Status         0
Poliza         0
dtype: int64

 DATOS NULOS DE GASTOS Y COSTOS 2023: 397
Fecha          0
Folio          0
UUID           0
RFC            0
Proveedor      0
TIPO GASTO     0
Descripción    0
MP             0
FP             0
TC             0
Importe        0
IVA            0
RET ISR        0
RET IVA        0
TOTAL MX       0
TOTAL SAT      0
Tipo           0
Status         0
Poliza         0
dtype: int64

### **Covertir a csv y descargar**

In [83]:
#Convertir archivo filtrado a CSV

fact.to_csv("Datos de Facturación_sn.csv")
det.to_csv("Detalle precios y productos fabricados 2022_sn.csv")
gyc20.to_csv("Gastos y costos 20_sn.csv")
gyc21.to_csv("Gastos y costos 21_sn.csv")
gyc22.to_csv("Gastos y costos 22_sn.csv")
gyc23.to_csv("Gastos y costos 23_sn.csv")

In [85]:
from google.colab import files 
  
  
files.download("Datos de Facturación_sn.csv")
files.download("Detalle precios y productos fabricados 2022_sn.csv")
files.download("Gastos y costos 20_sn.csv")
files.download("Gastos y costos 21_sn.csv")
files.download("Gastos y costos 22_sn.csv")
files.download("Gastos y costos 23_sn.csv")